version: '3.4'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: Users
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306